### ISSUE TITLE
Building consensus reads does not measure all pairwise distances

### ISSUE THREAD

**Issue by Haddox** [jbloomlab/dms_tools#10]
@jbloom: I think I found out why I was getting different alignment results when reads were ordered differently in the input FASTQ files. It relates to making sure that all reads are above `minreadidentity` relative to one another. Right now, `dms_tools` only measures distances relative to the FIRST read assigned to that barcode. It does not measure all pairwise distances. So depending on which read is the first read, the distances measured may differ, exceeding the `minreadidentity` in some cases but not others.

It seems like we should change the code to measure all pairwise distances. I could do this for python. However, currently the default code for the function that does this computation (`dms_tools.utils.BuildReadConsensus`) is written using C, which I do not have experience in.

What do you think should be the next step?

**Comment by Haddox** [comment]
FYI, the actual difference between my samples is pretty small: for one sample with ~2 million unique barcodes, only about 100-1,000 barcodes were differentially aligned/discarded.

**Comment by jbloom** [comment]
@Haddox: I think this is fixed. See this commit: https://github.com/jbloomlab/dms_tools/commit/f35b532a141599dc7e897681e9ba6c6f458593d2

I do not think it is worth adding the computational cost of doing all pairwise comparisons -- the current method of just comparing to the first read is sensible. However, now reads are sorted so that the first one is always the same regardless of input order.

Please check that this fixes the issue on your test data, and if so close this issue.

Note that this change is currently on `GitHub` but _not_ yet on `PyPI`, so install from source to test.

**Comment by Haddox** [comment]
This issue is fixed on my test data.
