### ISSUE TITLE
dms_barcodedsubamplicons without barcodes?

### ISSUE THREAD

**Issue by kristinalweber** [jbloomlab/dms_tools#13]
Hey! Got a quick question. If we did not barcode our variants, but rather have a sample of pooled variants for each round/condition which were randomly fragmented and sequenced (i.e. each pool is barcoded, but not each variant in each pool), can we still use dms_barcodedsubamplicons? Do we just set the barcode to a null value? Thanks!

**Comment by jbloom** [comment]
@kristinalweber: the way that `dms_barcodedsubamplicons` is currently set up, it will not handle reads without barcodes. If you just set the barcode to a null value, I think that will cause problems.

One hacky solution would just be to modify your FASTQ file to attach a unique barcode to each read, and then set the parameters to only require a single read per barcode. Would this work?

Otherwise, I can try to create an option so that the program does not require barcodes. If this would be helpful to you, I may be able to get it done in the next week. If you'd like me to do this, it would help if you can provide a bit more specifics on the form of your data and what you want to obtain so that I'm sure that I'm writing the program in a way that will work for you.

One caveat of course is that without barcodes, your read accuracy is going to be limited to the accuracy of Illumina sequencing, so you won't be able to see mutations at frequencies below the sequencing accuracy of 0.1 - 1%.

**Comment by kristinalweber** [comment]
Hey Jesse! I would love it if you could try to edit the program, as long as it's not too much work for you.


We have phagemid libraries which we are sequencing with a NextSeq, but did not barcode each variant within each pool. We are aware that this is less ideal (particularly as our target is longer than read length), but right now, we don't have the capacity to do individual barcodes for each variant. It would be useful to even be able to summarize the variants we are observing based on the shotgun reads - we did ~20M reads/sample pool and have been unable to work with the data very easily due to the high coverage.?


I'd be interested in your thoughts!

Kristina


Kristina L. Weber, PhD | Senior scientist
Zoetis | Genetics R&D | 333 Portage St, KZO300-387F, Kalamazoo, MI 49007
Office: 269.359.9591 (5-9591) | kristina.weber@zoetis.com<mailto:shana.hull@zoetis.com>
Visit Us http://www.zoetis.com/

________________________________

**Comment by jbloom** [comment]
Hi Kristina,

I'm going to close this issue and move our conversation to e-mail.

--Jesse
