### ISSUE TITLE
Add `median` option to `dms_merge`

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/dms_tools#16]
It appears that it would be useful to be able to easily get the median as well as the average. Is probably OK if this only works for `diffsel` as that is where it seems likely to be useful.

Maybe @mbdoud can do this?

**Comment by mbdoud** [comment]
Added this in ac04881ef867581bf77052d249018131a010b4ef. I think it would also be useful to optionally include the standard deviation in the output from `dms_merge` - as far as I can tell, as long as `dms_logoplot` and `dms_merge` become OK taking in mutdiffsel files with extra columns, this otherwise shouldn't present much of an issue?

**Comment by jbloom** [comment]
@mbdoud: Commit looks good.

We can add standard deviation if you'd like if you can make sure that it doesn't break other programs that you mention. But is this really useful? How much meaning can we assign to a standard deviation of three points, and how would this information be used?

**Comment by mbdoud** [comment]
Agree, it's perhaps less useful with only three points.  Some of the datasets I'm analyzing right now have 8 measurements - but we can just wait to add this later if it ever ends up being useful.
