### ISSUE TITLE
add pseudocount specifically to sample with lower depth in dms_diffselection

### ISSUE THREAD

**Issue by mbdoud** [jbloomlab/dms_tools#6]
`dms_diffselection` currently adds the value specified by `pseudocount` to the selected sample and scales the mock sample appropriately. This was in line with experimental design for some of my early experiments where I knew selected samples would have less depth and wanted to ensure that at least `pseudocount` counts were added to the lowest-depth sample.  

Instead it should add `pseudocount` to the sample with lower depth at the site and scale the other sample appropriately, in case the mock sample actually has lower depth.  This guarantees that in any situation, _at least_ `pseudocount` counts are added to both samples every time.

**Comment by jbloom** [comment]
@mbdoud and @orrzor: I think this issue is resolved by the changes I just pushed. Can one of you please test the current version on `GitHub` and make sure it behaves as you would like. Note that the changes are not yet pushed to `PyPI`, so be sure to use the `GitHub` version.

If it seems satisfactory, indicate that here and close the issue.

**Comment by mbdoud** [comment]
Looks good.
